# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Canadian Data Curation Forum
#email: your-email@example.com
author: Portage Curation Expert Group
#description: >- # this means to ignore newlines until "baseurl:"
#  This is the description of our site. It will appear in the document head meta (for
#  Google search results) and in the feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://data-curation.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: --
github_username:  data-curation

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

